project:
  type: book
  output-dir: docs

book:
  title: "Introdução aos Estudos Legislativos"
  author: Felipe Lamarca
  chapters:
    - index.qmd
    - part: Fundamentos
      chapters:
        - aulas/aula-1.qmd
        - aulas/aula-2.qmd
        - aulas/aula-3.qmd
        - aulas/aula-4.qmd
        - aulas/aula-5.qmd
        - aulas/aula-6.qmd
        - aulas/aula-7.qmd
        - aulas/aula-8.qmd
        - aulas/aula-9.qmd
        - aulas/bibliography.qmd
format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



