---
title: "Perspectiva distributivista pt. 2"
bibliography: ../bibliography.bib
author:
  - name: Felipe Lamarca
    email: felipelamarca@iesp.uerj.br
fontsize: 12pt
---

# @CainFerejohnFiorina1987PersonalVote {.unnumbered}

> Sociodemographic factors, such as political interest and civic concern, influence what and how much particular voters know. In our studies visibility increases dramatically with self-described political attentiveness, a relationship that probably explains a tendency for self-identified independents to have lower recall levels than partisants. [@CainFerejohnFiorina1987PersonalVote, p. 30]

> Over and above constituent characteristics, various characteristics of representatives themselves may increase their salience to constituents. Serving as prime minister is an extreme example, but less extreme possibilities are holding committee positions in the United States and serving on the ministerial ladder in Britain. [@CainFerejohnFiorina1987PersonalVote, p. 30]

> The most interesting correlates of visibility are those under the control of the representative: his or her personal activities, behavior, and allocation of available resources. Representatives can try to influence their level of visibility by spending time in their geographic districts, providing services for and assuming responsibilities in their constituencies, and publicizing their activities and accomplishments. [@CainFerejohnFiorina1987PersonalVote, p. 32-33]

> In short, more educated and more politically attentive constituents are more likely to know their representatives' names, as they are more likely to know many other things about politics and government. But name recall also is strongly related to constituents' reports about the ways in which they have come into contact with their representatives. This suggests that representatives have it within their power to make an impact on constituents by the activities they undertake. [@CainFerejohnFiorina1987PersonalVote, p. 36]

> Home style is in part a unique, individualized response of members to their districts and the natural inclinations of their personalities, but the public also holds stylized perceptions of representatives and their responsabilities, including expectations about how representatives should behave in office. These expectations derive in part from the common wisdom about how a contry's political system works but also from the class, ethnic, age, and social-economic background of constituents. To the extent that role expectations differ across districts, representatives will tailor their home styles accordingly. If representatives satify constituent expectations, their images will benefit and their electoral bases will be more secure. Conversely, failure to satisfy constituent expectations can adversely affect the representatives' image and weaken their electoral bases. [@CainFerejohnFiorina1987PersonalVote, p. 36]

> The better-educated, middle-class individuals in both countries favor a more policy-oriented role for their representatives, whereas the less well educated, working-class individuals favor a more service-oriented role. The education effect is particularly striking. [@CainFerejohnFiorina1987PersonalVote, p. 41-42]

> Race is a major continuing feature of American politics. Blacks ranked the roles of representatives very differently from the rest of the groups. They regarded policy as the least important activity and considered protecting the interests of the district and helping people as, respectively, second and third most important. [...]. To some extent, this racial difference arises from educational and class differences, but even when such factors are taken into account, racial differences in representative priorities remain. [@CainFerejohnFiorina1987PersonalVote, p. 42]

> In order to establish or improve their images, incumbents try to increase the number of favorable contacts they have with constituents through more personal visits, staff presence, casework solicitation, mailings, media appearances, and whatever else seems appropriate to particular districts.
>
> To say that incumbent have some control over their images through their activities is far from asserting that they have complete control. The ease of communicating a message to constituents varies with education, class, and inherent political interest. [@CainFerejohnFiorina1987PersonalVote, p. 47]


# @ShepsleWeingast1981StructureInduced {.unnumbered}

> In the area of legislative choice, social choice theorists have focused on the equilibrium properties of pure majority rule (PMR), operating according to the implicit belief that whatever is true about the PMR mechanism also applies to institutions based upon it. [...]. Over the past decade, the literature has marched toward increasingly general results about the nearly complete instability of the PMR [...]. These results in the context of the operating belief noted above seem to imply that the stability of legislative outcomes is tenuous at best. 
>
> In this paper, we develop an alternative view of institutions based upon majority rule and show that PMR is a special subset of this category, if not an extreme special case. By focusing upon the manner in which institutions transform PMR into a different legislative game (such as one with a committee system), we can show the properties of legislative institutions necessary for the existence of equilibrium. [@ShepsleWeingast1981StructureInduced, p. 503]

> We propose an alternative resolution of this anomaly. In our view, real-world legislative practices constrain the instability of PMR by _restricting_ the domain and the content of legislative exchange. [...]. Throughout, then, we hope to convey what we believe is a compelling case for answering Tullock's question, 'Why so much stability?' with 'Institutional arrangements do it!' It is the transformation of PMR into a more complex institutional arrangement, not logrolling and other forms of exchange, that produces 'so much' stability. [@ShepsleWeingast1981StructureInduced, p. 504]

> Assume an $m$-dimensional policy space, $X$, of feasible outcomes, and consider choice over $X$ by an $n$-person legislature. The legislature operates under the system of pure majority rule (PMR) in which any legislator (or group of legislators) may make proposals to alter the statos quo, $x^0$. Any proposal that commands a majority against $x^0$ beats it. In this setting, a _majority rule equilibrium_ (MRE) is an element of the feasible set that is unbeaten by any other element of $X$ in paired comparison. The results cited above show that under all but extreme circumstances -- specifically, smooth and convex preferences distributed in a precisely symmetrical fashion -- no MRE exists. Rather, for any point $x \in X$, there is a non-empty set of points, $W(x)$, called the _majority-rule win set at x_, each element of which commands the support of a majority against $x$. The lack of equilibrium implies that for all $x \in X, W(x) \neq \emptyset$. As a consequence, majority rule cycles exist, cycles which can be shown to extend over the entire policy space. [@ShepsleWeingast1981StructureInduced, p. 504-505]

> No matter what form of exchange is postulated, any point is dominated by some other proposed point that benefits a decisive coalition. For example, suppose some policy $x$ is arrived at through logrolling of coalition formation. Then, because $W(x)$ is non-empty at $x$, the losers, in combination with some of the winners at $x$, may propose some $y \in W(x)$ that makes this new majority better of at $y$ than at $x$. And nothing in the rules of the PMR game prohibits the new majority from forming and displacing is predecessor. This is the very essence of the nonexistence of equilibrium. [@ShepsleWeingast1981StructureInduced, p. 505]

> Let each legislator in an $n$-person legislature represent a geographical constituency which seeks a pork-barrel project. A project is parametrized by a scalar -- $x_j$ for the $j$th district -- measuring project size. Thus, an outcome of this context is an $n$-dimensional vector, $(x_1, ..., x_n)$, describing the various scales at which projects in each of the $n$ districts are to be built. Associated with each project are benefits concentrated exclusively in the district in which the project is sited -- $b_i (x_j) = 0$ if $i \neq j$ -- and costs distributed across all districts according to a fixed tax-sharing rule, $t_i c(x_j)$ being district $i$'s tax burden for district $j$'s project. The maximand for the $j$th legislator, assuming here that it is based exclusively on the net benefits secured by his district, is

$$
N_j (x_1, ..., x_n) = b_j (x_j) - t_j \sum^n_{i = 1} c(x_i)
$$

> The point here is that there is no natural stopping point for this choice institution so long as losers are not denied access to the agenda. And it does not matter that, as Tullock points out, the efficient policy that builds all projects at their most efficient scale, $x^e$, yields legislators highest _ex ante_ payoffs. Since at any proposal the majority win set is non-empty, it is always in the interest of those who prefer elements of this set to the original point to propose them. And, since nothing in the rules prevents them from doing so, they will. All we wish to note at this point is that $x^e$, like any other point under PMR, has a non-empty win set: $W(x^e) \neq \emptyset$. It is therefore vulnerable and holds no privileged theoretical status under PMR. We would, however, distinguish this argument from another entirely different argument, namely that $x^e$ might comprise the basis of an _ex ante_ agreement among legislators to alter institutional rules to guarantee $x^e$ as the outcome. This latter argument, which may well be what Tullock has in mind, involves transforming PMR into a different legislative game, namely one constrained by prior agreements on rules. [@ShepsleWeingast1981StructureInduced, p. 507]

> This transformation differs from logrolling and other forms of legislative exchange within PMR. Consequently, we must further emphasize in this context, since Tullock makes so much of it in his paper, _that logrolling accomplishes nothing_. If projects are voted on one at a time, in a non-cooperative fashion, then any such project will lose $n-1:1$ and the outcome is the zero vector, $x^0$. [...]. We conclude, consequently, that the promising direction of research involves an examination of transformations of the PMR game, transformations that _constrain_ the prospects of logrolling, not enhance it. [@ShepsleWeingast1981StructureInduced, p. 507]

> We have suggested above, moreover, that legislative exchange cannot rescue PMR from disequilibrium and may, in fact, exacerbate the instability. In this section, we show that institutional modifications of PMR may induce stability. Specifically, we show that _institutional restrictions on the domain of exchange_ induce stability, not legislative exchange per se. [@ShepsleWeingast1981StructureInduced, p. 507]

> To see how this works, note that though at all points $W(x)$ is non-empty, if at some point $y$, the rules of the game prohibit proposals in $W(y)$ from being placed on the agenda, or at least prohibit the would-be gainers from making these proposals, then $y$ may remain invulnerable or stable. This is not because there do not exist points that beat $y$ but rather because those favoring these points cannot place them on the agenda for consideration. [@ShepsleWeingast1981StructureInduced, p. 507-508]



# @Fiorina1989Keystone {.unnumbered}

# Anotações de aula

@CainFerejohnFiorina1987PersonalVote fazem uma análise comparando o legislativo da Inglaterra e o legislativo nos Estados Unidos. Em comum, o sistema eleitoral: pluralidade em distritos uninominais. A magnitude do distrito é fundamental: no Brasil, por exemplo, isso varia, mas lá a magnitude é a mesma em todos os distritos. A teoria e a pesquisa dos autores é fincada nessa ideia de distritos uninominais.

Os autores discutem _pork barrel_ e case work. O _case work_ é o trabalho específico de um caso particular, normalmente junto à burocracia -- isto é, facilitam a vida de pessoas junto ao estado, o que não implica legislação. O _pork barrel_, por outro lado, implica uma legislação -- trata-se de algo aprovado no legislativo mas que alcança especificamente o distrito. O pork barrel, por definição, é paroquial, alcançando grupos muito (sendo "muito" especificado pela sensibilidade do pesquisador) reduzidos. 

As atividades performadas pelos legisladores no município tendo em vista aumentar sua visibilidade e constituir redes locais de apoio. Uma dessas atividades é a assessoria prestada pelo parlamentar para a elaboração de projetos. O legislador, na capital, está informado sobre as possibilidades de financiamento de projetos do município ofertados pelo governo federal -- ou seja, o legislador leva informação aos atores políticos locais e leva consultoria para montar projetos e tramitá-la junto à burocracia.

O objetivo do livro não é estudar as políticas que estão saindo do legislativo. O que eles fazem é fixar o comportamento do eleitor; os autores tomam, como premissa, a ideia de que o parlamentar entende o eleitor como fixo no sentido de que só posso lidar com ele e melhorar o próprio desempenho eleitoral a partir dos serviços prestados.

Hipótese [@CainFerejohnFiorina1987PersonalVote]: o sistema inglês está em desequilíbrio porque ele é uninominal no nível eleitoral e centralizado no nível legislativo. Do ponto de vista eleitoral há uma pressão enorme para descentralizar o processo legislativo, que é centralizado nos partidos. Poucos recursos de propaganda, pouco dinheiro no gabinete, comissões não são permanentes... mas, na arena eleitoral, eles estão cada vez mais prestando serviço. A pressão é para descentralizar o processo legislativo -- afinal, é muito difícil mudar o sistema eleitoral, já que ele normalmente é constitucional. Em geral, quando há uma pressão desse tipo, ela recai sobre o processo legislativo. A previsão era de que haveria descentralização em algum ponto do tempo.

**Ticket splitting:** voto no presidente de acordo com a minha preferência partidária, ideologia, situação da economia, etc. Mas eu voto pro legislativo naquele candidato que resolve "o meu".

Por que meu texto [@ShepsleWeingast1981StructureInduced] está na teoria distributivista? Os resultados formais levam a que não há estabilidade nas decisões coletivas, mas isso está em contraposição à empiria. Se as teorias formais preveem tanta instabilidade, por que há tanta estabilidade? Gordon Tullock fundou a teoria da escolha pública a partir do livro Cálculo do Consenso, em que desenvolvem a ideia de ganhos mútuos da troca política. Isso acontece por logrolling: você vota minha proposta e eu voto a sua. Isso sintetiza a noção de ganhos mútuos da troca política.

No entanto, há custos de transação específicas à troca política. Por isso, @ShepsleWeingast1981StructureInduced usam a ideia de equilíbrio estruturalmente induzido por instituições. A teoria distributiva mostra o incentivo ao comportamento particularista, e daí poderíamos intuir: e por que não é um caos? Porque as instituições criam equilíbrio. Isso tudo é um diálogo dentro da teoria distributivista. A estrutura institucional induz equilíbrio porque elas limitam a barganha, e viabilizam os ganhos mútuos da troca -- isto é, viabilizam esse grande maquinário de distribuição de benefícios particularistas. [@ShepsleWeingast1981StructureInduced]