---
title: "Fundamentos"
bibliography: ../bibliography.bib
author:
  - name: Felipe Lamarca
    email: felipelamarca@iesp.uerj.br
fontsize: 11pt
---

# Anotações de aula {.unnumbered}

## Alguns conceitos iniciais {.unnumbered}

**Fire alarm:** conceito de o Legislativo deixar que o Executivo trabalhe e, no caso de algum tipo de ruído, ele "chia" -- isto é, fiscaliza.

**Core:** um conjunto de soluções possíveis; i.e., os pontos possíveis de serem alcançados a partir das preferências dos legisladores. Se o core é vazio, podemos chamar isso de várias maneiras, inclusive paralisia decisória. Isso vem da teoria dos jogos cooperativos.

## O conceito de racionalidade [@Gilboa2012RationalChoice] {.unnumbered}

A definição de racionalidade é o nosso ponto de partida. De saída, vale saber que a racionalidade é um atributo do indivíduo, mais especificamente das escolhas desses indivíduos. Essas escolhas têm determinadas características e essas características definem a racionalidade individual. Essas características são três:

1. **O indivíduo racional é capaz de distinguir alternativas:** diante de cursos de ação alternativos, o indivíduo racional consegue estabelecer conexão de causa e efeito, e essas consequências serão distintas;

$$
\begin{align*}
A &\rightarrow A^\prime \\
B &\rightarrow B^\prime \\
C &\rightarrow C^\prime
\end{align*}
$$

2. **O indivíduo racional é capaz de ordenar as alternativas**

$$
\begin{align*}
A > B \\
B > C 
\end{align*}
$$

3. **O ordenamento há de ser transitivo:** dado (2), $A > C$, e minha opção preferida é $A$.

Diante dessas alternativas, o indivíduo racional vai saber o que ele quer. Essa estabilidade é importante. Ele vai preferir aquilo que estiver mais alto no seu ordenamento.

**[definição]** A decisão coletiva é aquela que, uma vez tomada, vale para todos, independentemente da concordância. O menor grupo possível para tomar uma decisão coletiva (isto é, uma decisão de grupo) é aquele formado por 3 pessoas. De fato, só há decisão em uma dupla se há consenso. Para que uma decisão coletiva seja tomada, precisamos de uma **regra**. Essa regra estabelece o procedimento através do qual as decisões individuais serão amalgamadas e será definida a decisão coletiva. A regra mais famosa que existe, derivada do utilitarismo, é a regra da maioria.

**Em resumo:** os nossos indivíduos se comportam racionalmente (_behavior_). Esses indivíduos interagem entre si de acordo com uma regra para produzir decisões coletivas.

Suponha esses 3 indivíduos e suas ordenações de preferência: $X$ ($A > B > C$), $Y$ ($B > C > A$) e $Z$ ($C > A > B$). Se temos $A$ contra $B$, $A$ ganha; para $B$ contra $C$, $B$ ganha; mas para $A$ contra $C$, $C$ ganha, já que $A$ é preferida contra $B$ e $B$ é preferida contra $C$ -- uma contradição. Não há transitividade, então a racionalidade não pode ser aplicada. Esse é o [Paradoxo de Condorcet](https://pt.wikipedia.org/wiki/Paradoxo_de_Condorcet).

**[Teorema do Júri:](https://pt.wikipedia.org/wiki/Teorema_do_j%C3%BAri_de_Condorcet)** se você assume que cada indivíduo tem uma probabilidade um pouco maior que 50% de tomar a decisão certa, qual é a probabilidade de o júri (coletivo de indivíduos) acerte? (i.e., julgue corretamente entre culpado ou inocente) A ideia do teorema é que, se eu aumento o eleitorado, a probabilidade de tomar a decisão certa aumenta.

**A decisão coletiva não pode ser pensada com os mesmos atributos da decisão individual**. 

Como, então, estabilizamos as decisões coletivas? Uma solução muito boa foi a solução de Duncan Black: o [Teorema do Eleitor Mediano](https://pt.wikipedia.org/wiki/Teorema_do_eleitor_mediano). Trabalhamos, aqui, com a noção de espaço político -- ou seja, existe um espaço de conflito. Há também uma restrição para o formato das preferências: a noção de "pico único" -- a preferência possui um ponto de máximo, e à medida que eu me afasto desse máximo, a utilidade diminui.

Eu defino os agentes em um espaço unidimensional (i.e., uma reta) -- o espaço do conflito político, e esses agentes estão distribuídos de acordo com os seus respectivos pontos ideais. O pressuposto importante (que nos permitimos fazer por conta da teoria da racionalidade) é que eu sempre prefiro um ponto mais próximo do meu ponto ideal do que um ponto distante. Se eu aplico essa lógica para todos os eleitores, eu chego à conclusão de que o ponto de equilíbrio é a posição do eleitor **mediano**. A preferência do eleitor mediano é aquela que ganha de todas as demais preferências.

Mas e aí? A vida política é multidimensional, então os pressupostos de Duncan Black fazem com que a teoria perca operacionalidade. Dito isso, a realidade política não é o caos. Como há tanta estabilidade se tudo indica que o resultado seria o caos? Regras! Ou melhor, **instituições**. O que as instituições fazem é "chapar" o espaço do conflito, tornando-o unidimensional ou no mínimo tornando as preferências mais homogêneas. As instituições **forjam** um espaço unidimensional -- nos espaços decisórios, teremos apenas pessoas com preferências próximas e, portanto, barganham nos mesmos termos.

## Neo-institucionalismo [@DiermeierKrehbiel2003Institutionalism] {.unnumbered}

1. O indivíduo, decisor, tem a racionalidade como atributo principal
2. As regras, _constraints_, são limitadores

A equação fundamental do meu fenômeno de interesse é:

$$
\text{Fenomeno político} = \text{Preferência} + \text{Regra}
$$

Precisamos identificar quem são os meus decisores e definir as suas distribuições de preferências. Nada mais importa na análise do indivíduo com exceção disso. O segundo passo é identificar quais são os constrangimentos dos indivíduos na busca pelas suas preferências -- tendo essas duas coisas, serei capaz de construir meu argumento sobre o fenômeno político de interesse. Daí eu derivo algum tipo de argumento, hipóteses, e o teste empírico.

Isso é uma maneira de modelar a realidade. Precisamos, então, assumir algumas coisas. Em primeiro lugar, assumimos que as regras são exógenas ao indivíduo e fixas -- i.e., do ponto de vista analítico, assumimos que as regras são dadas, embora, é claro, em algum dado momento elas sejam criadas pelos próprios indivíduos. Depois, assumimos que as preferências individuais são dadas, embora variem de indivíduo para indivíduo.

Como o Neo-institucionalismo se diferencia da concepção de _core_? O que a teoria do _core_ faz é mostrar como, num espaço político multidimensional, as instituições forjam um espaço político unidimensional no qual há soluções possíveis (onde o _core_ não é vazio). Nesse contexto, os indivíduos vão barganhar as soluções de equilíbrio. Exatamente onde a solução vai estar dentro do _core_ é uma questão de barganha, isto sendo dizer sob quais condições você aceita tal ou tal solução. A barganha reduz o _core_ até chegar a uma solução.

**Uma aplicação:** quando chega no Legislativo, o espaço do conflito é absolutamente multidimensional. Isso é caos, lógico. As instituições criam fóruns de decisão unidimensionais, para discutir assuntos únicos -- no caso do legislativo norte-americano[^1], as comissões. É isso que explica o surgimento de comissões pela teoria do _core_. 

Quando eu forjo a unidimensionalidade, eu crio um ambiente de pessoas extremamente comprometidas com esse único tema. Mas isso afasta as decisões da comissão do parlamentar mediano! Observe, no entanto: se isso vai passar pelo plenário, como eu posso esperar que haja aquiescência, se os acordos que vêm da comissão são distantes do parlamentar mediano? É por isso que a ideia de _core_ não funciona -- não é essa a metodologia adequada para entender a dinâmica política. Não podemos usar uma ideia cooperativa, mas sim uma não-cooperativa [@DiermeierKrehbiel2003Institutionalism].

O jogo não-cooperativo mais famoso é o dilema do prisioneiro. Nesse caso, o jogo é ganho pela estratégia dominante: independente do que os outros façam, eu tomo sempre a mesma ação. Metodologicamente, preferimos não usar a ideia de barganha como a forma de analisar um fenômeno político.

**Equilíbrio de Nash:** descreve uma situação em que nenhum jogador tem incentivo para mudar sua estratégia unilateralmente, dado o que os outros jogadores estão fazendo. Ou seja: eu defino como melhor resposta dado o que o outro está fazendo. Ninguém tem incentivo para mudar o seu comportamento -- portanto, o dilema do prisioneiro é um caso particular do equilíbrio de Nash.

É importante não confundir equilíbrio com soluções ótimas. A definição de equilíbrio de Nash é que cada um escolhe o melhor para si dado o que o outro está fazendo. Esse equilíbrio, no entanto, não significa que eu estou fazendo o que poderia ser ótimo no conjunto.

Os constrangimentos definem o que eu e os outros podem fazer, e isso faz parte do jogo. Eu adoto um comportamento, os demais observam esse comportamento, e as pessoas fazem o mesmo. Nesse caso, há equilíbrio, porque ninguém tem incentivo para mudar. Isso é diferente do _core_. O que @DiermeierKrehbiel2003Institutionalism defende é que essa é a melhor estratégia para analisar o fenômeno político: as regras são fixas, os atores tomam as melhores escolhas dado o que os demais estão fazendo, modelamos a interação, encontramos o equilíbrio e testamos hipóteses.


[^1]: Afinal, isso tudo foi pensando em vista da política dos Estados Unidos.